# Generated by Django 2.1.8 on 2019-05-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=1000)),
                ('pwd', models.IntegerField(default=0)),
                ('number', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.CharField(default='', max_length=1000)),
                ('owner_number', models.IntegerField(default=0)),
                ('concert_name', models.CharField(default='', max_length=1000)),
                ('singer', models.CharField(default='', max_length=1000)),
                ('concert_date', models.IntegerField(default=0)),
                ('post_date', models.IntegerField(default=0)),
                ('owner_pwd', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('now_capacity', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='chosen_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Post'),
        ),
    ]
