# Generated by Django 2.1.8 on 2019-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner_number',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
