# Generated by Django 2.1.8 on 2019-05-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190504_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='chosen_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Post'),
        ),
    ]
