# Generated by Django 2.1.8 on 2019-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190504_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='concert_date',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
