# Generated by Django 2.1.7 on 2019-05-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='concert_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
